name: wepool
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Define the version and build number of your app
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# ✅ Dependencies for your Flutter project
dependencies:
  flutter:
    sdk: flutter

  # Icons and UI Libraries
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  google_fonts: ^6.1.0
  lottie: ^3.3.1

  # Logging and Utilities
  logger: ^2.5.0
  device_info_plus: ^9.1.2

  # Storage and State Management
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  get_it: ^7.2.0

  # 📌 Flutter Launcher Icons (Used to generate app icons)
  flutter_launcher_icons: ^0.14.3

# ✅ Dev Dependencies (Used for testing and linting)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ✅ Flutter settings
flutter:
  uses-material-design: true

  # ✅ Assets used in the app
  assets:
    - assets/images/
    - assets/icons/
    - assets/anim/done_animation.json

  # ✅ Custom Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/font_poppins_regular.ttf

# ✅ Configure App Icons for Android & iOS
flutter_launcher_icons:
  android: "launcher_icon" # Enables Android icon generation
  ios: true # Enables iOS icon generation
  image_path: "assets/icons/lg_app.png" # Path to the main icon image
  min_sdk_android: 21 # Minimum Android SDK (default is 21)

  # ✅ Web App Icon Settings
  web:
    generate: true
    image_path: "assets/icons/lg_app.png"
    background_color: "#FFFFFF" # Change background color if needed
    theme_color: "#000000"

  # ✅ Windows App Icon Settings
  windows:
    generate: true
    image_path: "assets/icons/lg_app.png"
    icon_size: 48 # Default: 48, Min: 48, Max: 256

  # ✅ macOS App Icon Settings
  macos:
    generate: true
    image_path: "assets/icons/lg_app.png"
